# Generated by Django 3.2.5 on 2022-04-19 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacao',
            options={'verbose_name': 'Importação', 'verbose_name_plural': 'Importações'},
        ),
        migrations.AddField(
            model_name='importacao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importacao',
            name='data_hora_importacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da importação'),
        ),
    ]
