# Generated by Django 3.2.5 on 2022-04-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0002_auto_20220419_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='importacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importacoes.importacao', verbose_name='Importação'),
            preserve_default=False,
        ),
    ]
